# Generated by Django 5.1.4 on 2025-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('corte_barba', 'Corte y Barba'), ('ninos', 'Corte para Niños'), ('tratamiento', 'Tratamiento Facial'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure')], max_length=20)),
                ('numero_reserva', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
