# Generated by Django 5.1.4 on 2025-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15),
        ),
    ]
